/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomRoomIdRouteImport } from './routes/room/$roomId'
import { Route as ApiV4RoomsRouteImport } from './routes/api/v4/rooms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdRoute = RoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV4RoomsRoute = ApiV4RoomsRouteImport.update({
  id: '/api/v4/rooms',
  path: '/api/v4/rooms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/api/v4/rooms': typeof ApiV4RoomsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/api/v4/rooms': typeof ApiV4RoomsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/api/v4/rooms': typeof ApiV4RoomsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/room/$roomId' | '/api/v4/rooms'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/room/$roomId' | '/api/v4/rooms'
  id: '__root__' | '/' | '/room/$roomId' | '/api/v4/rooms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RoomRoomIdRoute: typeof RoomRoomIdRoute
  ApiV4RoomsRoute: typeof ApiV4RoomsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId': {
      id: '/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof RoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v4/rooms': {
      id: '/api/v4/rooms'
      path: '/api/v4/rooms'
      fullPath: '/api/v4/rooms'
      preLoaderRoute: typeof ApiV4RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RoomRoomIdRoute: RoomRoomIdRoute,
  ApiV4RoomsRoute: ApiV4RoomsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
